### ISSUE TITLE
Deprecate built-in `github` formatter

### ISSUE THREAD

**Issue by ybiquitous** [xt0rted/stylelint-actions-formatters#187]
Hey @xt0rted,

Thanks for creating this nice package! I am a maintainer of Stylelint.

I am contacting you since our Stylelint team plans to deprecate the [built-in `github` formatter](https://stylelint.io/user-guide/options#formatter) and considers `stylelint-actions-formatters` as an alternative.

Do you have any problems if we describe your package in our documentation (e.g. changelog or migration guide)? Please feel free to let me know of any concerns.

**Comment by ybiquitous** [comment]
Thank you!

**Comment by ybiquitous** [comment]
I'm closing this issue since I just want to confirm.

**Comment by xt0rted** [comment]
@ybiquitous these formatters aren't actually needed to create annotations in GitHub Actions, for that you just need [my problem matcher](https://github.com/xt0rted/stylelint-problem-matcher) and to use the string formatter.

What these formatters do is fix the file paths when you run from a sub folder like so:

https://github.com/xt0rted/stylelint-actions-formatters/blob/0c9cbde7fab8933fd948d05e3bebd69970d18416/.github/workflows/ci.yml#L48-L56

The output of that:

```text
test/errors.css
  1:9  ✖  Unexpected empty block  block-no-empty

test/warnings.css
  1:1  ⚠  Unexpected empty comment  comment-no-empty
  6:3  ⚠  Unexpected empty comment  comment-no-empty

✖ 3 problems (1 error, 2 warnings)
```

With the built-in formatters the file paths won't include `test/`, and since annotation paths need to be relative to the repo root they won't be created.

While publishing v16 releases just now I noticed the annotations aren't being created. I'm hoping I just need to publish a new version of the problem matcher since it's out of date.

For the time being these formatters will give the correct file paths in the build logs, but I don't think you'll be able to get annotations until I fix the problem matcher. I'm going to look at that over the weekend and will let you know when it's all working again in case there's documentation that needs to be updated too.

**Comment by ybiquitous** [comment]
Thank you for sharing the info! 😊

**Comment by tagliala** [comment]
Hello, maybe something changed or `npx` is not supported, but at the moment I'm not able to use this suggested formatter or the action (which also has warnings)

The deprecated formatter is the only approach that worked for me here, as a non-JavaScript developer:

Ref: diowa/ruby3-rails7-bootstrap-heroku#984, xt0rted/stylelint-problem-matcher#592
